version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    depends_on:
      - rabbitmq
    depends_on:
      - zipkinDB
    environment:
      - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkinDB
      - MYSQL_PORT=3336
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    restart: always
    
  rabbitmq:
    image: rabbitmq:3-management
    mem_limit: 300m
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  
  zipkinDB:
    image: mysql:8.0
    container_name: zipkinDB
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservices
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3336:3306
    volumes:
      - C:/Dev/DockerVolumes/microservices/zipkin/mysql/dbdata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    container_name: zipkinPMA
    links:
      - zipkinDB
    environment:
      PMA_HOST: zipkinDB
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8181:80
volumes:
  dbdata: